import sys
#s = "TGGTATTGTATGTATTGTACGTATTGTATATTGTATATTGTACCGTATTGTAATATTGTATATTGTAGGTGTAGCTATTGTATATTGTACCTATTGTATATTGTATTATTGTATTATTGTATTATTGTATATTGTAAATATTGTACCATATTGTATATTGTATATTGTACCTATTGTACTATTGTAGTATTGTAAGGGTATTATTGTAACATTATTGTAGATATTGTAACACTTGCTATTGTATATTGTATCAGGTTCCAATTATTGTATATTGTACCTATTGTATATTGTATTATTGTATATTGTAGTATATTGTACTATTGTAGTCGTGGATATTGTAGTTCCTATTGTAATATTGTATATTGTATATTGTATATTGTATATTGTACTATTGTAGTATTGTAATTATTGTACAGGTATTGTATATTGTATATTGTATTGACGGCCGTATTGTATATTGTAAATATTGTAGTATTGTACTGTATTGTATATTGTATATATTGTAAGGACTAGGCACCTATTGTAATATTGTATATTGTATTTGCTGGATATTGTACGTATTGTACTTATTGTAGGACTATTGTATATATTGTACTTATTGTAGTATTGTACCATATTGTATTGTAGATTATTGTAGTTGCTGAGTTATTGTATATTGTAGCATATTGTATATTGTAGGCGTTATATTGTATTATTGTATATTGTACTATTGTATTATTGTAAATTATTGTACTCCGATATTGTATTATTGTATTATTGTAGACATTATTGTATATTGTATATTGTATCGTATTGTATATTGTAAATACTATTGTAGTATTGTATATTGTAGTTGTTATTGTACTGTATTGTATGTTATTGTATCGGTAAATATTGTATCATCTATTGTATATTGTA"
#t = "TATTGTATA"

s = sys.argv[1].strip()
t = sys.argv[2].strip()

results = []
for i,c in enumerate(s):
    idx = s.find(t,i)
    idx += 1
    if idx not in results:
        results.append(idx)

print(results[:-1])
res = results[:-1]

print(' '.join(map(str, results)))
